### ISSUE TITLE
Custom pack counts for draft and sealed

### ISSUE THREAD

**Issue by tooomm** [dr4fters/dr4ft#64]
**Draft**
- [ ] 4 Pack Draft - Needed for [dino-sized Drafts](https://magic.wizards.com/en/articles/archive/news/announcing-dino-sized-weekend-and-ixalan-mid-season-league-2017-09-18)
- [ ] 6 Pack Draft - Needed for [Two Headed Giant Draft](https://blogs.magicjudges.org/2hg/faq/) (we would need to be able to pick two cards out of each pack to support that official format)

**Sealed**
- [ ] 1 Pack Sealed https://github.com/dr4fters/dr4ft/issues/47 - Needed for [Magic League](https://magic.wizards.com/en/event-types/magic-league)
- [ ] 3 Pack Sealed https://github.com/dr4fters/dr4ft/issues/47 - Needed for [Magic League](https://magic.wizards.com/en/event-types/magic-league)
- [x] 4 Pack Sealed https://github.com/dr4fters/dr4ft/pull/12
- [ ] 8 Pack Sealed https://github.com/dr4fters/dr4ft/issues/41, #114 - Needed for [Two Headed Giant Sealed](https://blogs.magicjudges.org/2hg/faq/)
- [ ] 12 Pack Sealed https://github.com/dr4fters/dr4ft/issues/41, #114 - Needed for [Team Sealed](https://magic.wizards.com/en/game-info/gameplay/formats/team-sealed-deck)

<br>

**I guess it would be best to have fully customizable packs for sealed and draft instead all this check boxes for different pre-configured pack counts**
Also, because there is a lot of crazy stuff out there that we can't keep up with:
- [36-pack Chaos Sealed](https://www.reddit.com/r/magicTCG/comments/5098lt/grand_prix_portland_36pack_chaos_sealed/) at GP Portland
- [12-pack 2HG Sealed](http://gplondon.cfbevents.com/#schedule) at GP London
- [Full Box 2HG Sealed](http://gplondon.cfbevents.com/#schedule) at GP London
- ...

**Comment by tooomm** [comment]
I want to note here, that we talked in Gitter about this some time ago.
@dev-id came up with something like this to add/remove packs and support all custom quantities:

```
"Rivals of Ixalan (RIX)" [-]
"Rivals of Ixalan (RIX)" [-]
[+]
```

**Comment by HerveH44** [comment]
I'll look at this one soon I think. It should only be a question of adding a new variable "pack number" on GUI.

Is there any problem by doing so? I mean if the user can insert "10 packs" for each player, I don't see any problem...

**Comment by ancestral** [comment]
This is important for Battlebond, as 2HG drafting wants 4 packs.
